version: '3'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: vedlena/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: vedlena/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: vedlena/foodgram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media/
    ports:
      - 8000:80
    depends_on:
      - db